Repository DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth, pull requests merged in 2022-07, with the labels that each got.

#6 [FEAT] 기본 UI 작업
  .DS_Store
  Pikipick/.DS_Store
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/.DS_Store
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/Contents.json
  Pikipick/Pikipick/Assets.xcassets/MainImage.imageset/Contents.json
  Pikipick/Pikipick/Assets.xcassets/MainImage.imageset/mainImage.png
  Pikipick/Pikipick/Assets.xcassets/PrimaryColor.colorset/Contents.json
  Pikipick/Pikipick/Base.lproj/Main.storyboard
  Pikipick/Pikipick/Model/SettingModel.swift
  Pikipick/Pikipick/ViewController.swift
  Pikipick/Pikipick/ViewController/Main/LicenseViewController.swift
  Pikipick/Pikipick/ViewController/Main/MainViewController.swift
  Pikipick/Pikipick/ViewController/Main/ParticipateViewController.swift
  Pikipick/Pikipick/ViewController/Main/SettingTableViewController.swift
Labels: enhancement

#10 Setting view/#8
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/Model/SettingModel.swift
  Pikipick/Pikipick/Settings.bundle/License.plist
  Pikipick/Pikipick/Settings.bundle/Root.plist
  Pikipick/Pikipick/Settings.bundle/en.lproj/Root.strings
Labels: enhancement

#11 [FEAT] AudienceView (#7)
  Pikipick/.DS_Store
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/AudienceStoryboard.storyboard
  Pikipick/Pikipick/AudienceViewController.swift
Labels: enhancement, fix

#14 [FEAT] Multipeer Connectivity 추가 (#13)
  Pikipick/.DS_Store
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/Extensions/String+.swift
  Pikipick/Pikipick/Info.plist
  Pikipick/Pikipick/Model/Constants.swift
  Pikipick/Pikipick/MultipeerConnectivity/PresenterDetector.swift
  Pikipick/Pikipick/MultipeerConnectivity/SessionAudience.swift
  Pikipick/Pikipick/MultipeerConnectivity/SessionPresenter.swift
Labels: enhancement

#19 Participate view/#15
  Pikipick/Pikipick/AudienceStoryboard.storyboard
  Pikipick/Pikipick/AudienceViewController.swift
  Pikipick/Pikipick/Base.lproj/Main.storyboard
  Pikipick/Pikipick/ViewController/Main/ParticipateViewController.swift
Labels: enhancement

#22 Custom Alert 구현
  Pikipick/.DS_Store
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/Base.lproj/Main.storyboard
  Pikipick/Pikipick/Info.plist
  Pikipick/Pikipick/LocalNetworkPrivacy.swift
  Pikipick/Pikipick/Model/Segment.swift
  Pikipick/Pikipick/ViewController/Main/MainViewController.swift
  Pikipick/Pikipick/ViewController/Main/ParticipateViewController.swift
Labels: enhancement

#25 [FEAT] PresentaitonView (#12)
  .DS_Store
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/ButtonActionView.swift
  Pikipick/Pikipick/ButtonAnimView.swift
  Pikipick/Pikipick/PresentationView.swift
Labels: enhancement, fix

#28 [FIX] Custom alert/#20
  Pikipick/.DS_Store
  Pikipick/Pikipick/Assets.xcassets/.DS_Store
  Pikipick/Pikipick/Base.lproj/Main.storyboard
  Pikipick/Pikipick/ViewController/.DS_Store
  Pikipick/Pikipick/ViewController/Main/MainViewController.swift
Labels: fix

#30 [FEAT] Add haptic/#29
  Pikipick/Pikipick/AudienceStoryboard.storyboard
  Pikipick/Pikipick/AudienceViewController.swift
Labels: enhancement, fix

#35 [DESIGN] 샘플 앱 아이콘 추가 (#34)
  FEH-Pikipick.html
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/100.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/1024.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/114.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/120.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/144.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/152.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/167.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/180.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/20.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/29.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/40.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/50.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/57.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/58.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/60.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/72.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/76.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/80.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/87.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: design

#39 [FIX] Local Network 권한 획득 딜레이 (#38)
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/Info.plist
  Pikipick/Pikipick/LocalNetworkAuthorization.swift
  Pikipick/Pikipick/LocalNetworkPrivacy.swift
  Pikipick/Pikipick/ViewController/Main/MainViewController.swift
Labels: fix

#40 [FIX] MainView landscape mode 제약 (#9)
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/AppDelegate.swift
  Pikipick/Pikipick/AppUtility.swift
  Pikipick/Pikipick/PresentationView.swift
Labels: fix

#44 [FEAT] Multipeer Connectivity 기능 추가 (#43)
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/ButtonAnimView.swift
  Pikipick/Pikipick/MultipeerConnectivity/MultipeerDataModel.swift
  Pikipick/Pikipick/MultipeerConnectivity/MultipeerVoteDataModel.swift
  Pikipick/Pikipick/MultipeerConnectivity/SessionAudience.swift
  Pikipick/Pikipick/MultipeerConnectivity/SessionPresenter.swift
Labels: enhancement

#62 [FEAT] ParticipateView Custom (#50)
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/Assets.xcassets/Colors/gradientFirstColor.colorset/Contents.json
  Pikipick/Pikipick/Assets.xcassets/Icons/icn_chevron_right_32px_black.imageset/Contents.json
  Pikipick/Pikipick/Assets.xcassets/Icons/icn_chevron_right_32px_black.imageset/icn_chevron_right_32px_black.png
  Pikipick/Pikipick/Assets.xcassets/Icons/icn_chevron_right_32px_black.imageset/icn_chevron_right_32px_black@2x.png
  Pikipick/Pikipick/Assets.xcassets/Icons/icn_chevron_right_32px_black.imageset/icn_chevron_right_32px_black@3x.png
  Pikipick/Pikipick/Base.lproj/Main.storyboard
  Pikipick/Pikipick/Cells/ParticipateTableViewCell.swift
  Pikipick/Pikipick/Extensions/UIButton+.swift
  Pikipick/Pikipick/ViewController/Main/ParticipateViewController.swift
Labels: enhancement

#59 [FEAT] Presentation View Custom Menu Button 추가 (#52)
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/Assets.xcassets/Colors/closeButtonColor.colorset/Contents.json
  Pikipick/Pikipick/Assets.xcassets/Colors/dividerColor.colorset/Contents.json
  Pikipick/Pikipick/MultipeerConnectivity/Model/Constants.swift
  Pikipick/Pikipick/MultipeerConnectivity/Model/MenuButtonViewType.swift
  Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
  Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
  Pikipick/Pikipick/Utils/Extensions.swift
Labels: enhancement

#68 Feat/#57
  Pikipick/.DS_Store
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/.DS_Store
  Pikipick/Pikipick/Assets.xcassets/.DS_Store
  Pikipick/Pikipick/ButtonActionView.swift
  Pikipick/Pikipick/ButtonAnimView.swift
  Pikipick/Pikipick/Extensions/Color+.swift
  Pikipick/Pikipick/Extensions/UIScreen+.swift
  Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
  Pikipick/Pikipick/PresentationView.swift
Labels: enhancement

#74 [FEAT] QuestionsView 구현 (#61)
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/AudienceStoryboard.storyboard
  Pikipick/Pikipick/AudienceViewController.swift
  Pikipick/Pikipick/Model/Segment.swift
  Pikipick/Pikipick/QuestionsStoryboard.storyboard
  Pikipick/Pikipick/ViewController/QuestionsViewController.swift
Labels: enhancement

#78 TableView Cell 선택 색상 수정
  Pikipick/Pikipick/ViewController/Main/ParticipateViewController.swift
Labels: enhancement

#77 [FEAT] Multipeer Vote QnA 데이터 연결 (#71)
  Pikipick/.DS_Store
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/AudienceViewController.swift
  Pikipick/Pikipick/ButtonActionView.swift
  Pikipick/Pikipick/Extensions/RotationDetecter.swift
  Pikipick/Pikipick/MultipeerConnectivity/SessionAudience.swift
  Pikipick/Pikipick/MultipeerConnectivity/SessionPresenter.swift
  Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
  Pikipick/Pikipick/PresentationView.swift
  Pikipick/Pikipick/ViewController/PresentationSubViews/PresentationQuestionView.swift
  Pikipick/Pikipick/ViewController/PresentationSubViews/PresentationVoteListView.swift
  Pikipick/Pikipick/ViewController/PresentationSubViews/PresentationVoteView.swift
  Pikipick/Pikipick/ViewController/PresentationSubViews/RootPresentationView.swift
  Pikipick/Pikipick/ViewController/QuestionsViewController.swift
Labels: enhancement

#82 [DESIGN] App Logo
  Pikipick/Pikipick/.DS_Store
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/100.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/1024.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/114.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/120.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/128.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/144.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/152.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/16.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/167.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/172.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/180.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/196.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/20.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/216.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/256.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/29.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/32.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/40.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/48.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/50.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/512.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/55.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/57.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/58.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/60.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/64.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/72.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/76.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/80.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/87.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/88.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: design

#81 [FEAT] Emoji 전송 시 Haptic 추가 (#56)
  Pikipick/Pikipick.xcodeproj/project.pbxproj
  Pikipick/Pikipick/AudienceViewController.swift
  Pikipick/Pikipick/Extensions/HapticManager.swift
Labels: enhancement

#85 [FEAT] Clear Button Alert 추가 (#84)
  Pikipick/Pikipick/ViewController/PresentationSubViews/RootPresentationView.swift
Labels: enhancement

#86 Presentation 하단 이모지 영역 색상 수정, 메시지 영어로 변경 Fix/#83
  Pikipick/Pikipick/Base.lproj/Main.storyboard
  Pikipick/Pikipick/ButtonActionView.swift
  Pikipick/Pikipick/Model/Segment.swift
  Pikipick/Pikipick/MultipeerConnectivity/Model/MenuButtonViewType.swift
  Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
  Pikipick/Pikipick/ViewController/Main/MainViewController.swift
  Pikipick/Pikipick/ViewController/PresentationSubViews/PresentationVoteView.swift
Labels: fix, design

#89 [DESIGN] App Logo
  Pikipick/Pikipick/Assets.xcassets/.DS_Store
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/100.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/1024.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/114.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/120.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/128.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/144.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/152.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/16.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/167.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/172.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/180.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/196.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/20.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/216.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/256.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/29.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/32.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/40.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/48.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/50.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/512.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/55.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/57.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/58.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/60.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/64.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/72.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/76.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/80.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/87.png
  Pikipick/Pikipick/Assets.xcassets/AppIcon.appiconset/88.png
Labels: design

#91 [FIX] gradient 추가, 버튼 버그 수정
  Pikipick/Pikipick/AudienceStoryboard.storyboard
  Pikipick/Pikipick/AudienceViewController.swift
  Pikipick/Pikipick/CircularProgressBarView.swift
  Pikipick/Pikipick/Extensions/UIButton+.swift
Labels: fix
